services:
  postgres-sample:
    image: postgres:17
    container_name: tshirt_store_container
    environment:
      POSTGRES_PASSWORD: nerdery_2026
      POSTGRES_USER: postgres
      POSTGRES_DB: tshirt_store_nerderydb
    restart: always
    ports:
      - 5432:5432
      # add your port in case you have 5432 in use e.g 5434:5432 for 5434
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
